<?php


namespace admin\models;


use yii\db\ActiveRecord;

/**
 * @property $id
 * @property $title
 * @property $image
 * @property $price
 * @property $is_active
 * @property $participants_ids
 * @property $winner_id
*/

class Auctions extends ActiveRecord
{
    public $winner_phone;
    public static function tableName()
    {
        return 'auctions'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['id','is_active','price','participants_ids','winner_id'], 'safe'],
            [['price','winner_id'], 'integer'],
            [['title', 'image'], 'required']
        ]; // TODO: Change the autogenerated stub
    }
}