<?php


namespace admin\models;


use yii\db\ActiveRecord;

class Categories extends ActiveRecord
{
    public static function tableName()
    {
        return 'categories'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['id','image','popular'],'safe']
        ]; // TODO: Change the autogenerated stub
    }
    public function getProducts(){
        return $this->hasMany(Products::class,['category_id'=>'id']);
    }
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $session = \Yii::$app->session;
            $this->image = 'assets/categories/images/'.$session->get('category_image');
            $session->set('category_image',null);
        }
        else{
            $session = \Yii::$app->session;
            $this->image = 'assets/categories/images/'.$session->get('category_image');
            $session->set('category_image', null);
        }// TODO: Change the autogenerated stub
        return true;
    }
}