<?php


namespace admin\models;


use yii\db\ActiveRecord;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use yii\helpers\Url;

class Categories extends ActiveRecord
{
    public static function tableName()
    {
        return 'categories'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['id','image','popular','slug'],'safe']
        ]; // TODO: Change the autogenerated stub
    }
    public function getProducts(){
        return $this->hasMany(Products::class,['category_id'=>'id']);
    }
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $session = \Yii::$app->session;
            if ($session->get('category_image')){
                $this->image = 'assets/categories/images/'.$session->get('category_image');
            }

            if (!$this->slug) {
                $this->slug = StringHelper::url($this->title);
            }
        }
        else{
            if (!$this->slug && !Categories::findOne(['id'=>$this->id])->slug){
                $this->slug = StringHelper::url($this->title);
            }

            $session = \Yii::$app->session;
            if ($session->get('category_image')!=null || trim($session->get('category_image'))!=''){
                $this->image = 'assets/categories/images/'.$session->get('category_image');
            } else{
                $this->image = Categories::findOne(['id'=>$this->id])->image;
            }
        }// TODO: Change the autogenerated stub
        return true;
    }

    public function afterSave($insert, $changedAttributes)
    {
        $session = \Yii::$app->session;
        $session->set('category_image', null);
    }
}