<?php


namespace admin\models;


use yii\db\ActiveRecord;

class OrderAmounts extends ActiveRecord
{
    public static function tableName()
    {
        return 'order_amounts'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['order_id','amount'],'required'],
            [['id'], 'safe']
        ]; // TODO: Change the autogenerated stub
    }
}