<?php


namespace admin\models;


use yii\db\ActiveRecord;
/*
 * @property is_active
 *
*/
class Products extends ActiveRecord
{
    public static function tableName()
    {
        return 'products'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [
                ['title','price','barcode','category_id','short_description'], 'required',
            ],
            [
                ['image','popular','is_active'],'safe'
            ]
        ]; // TODO: Change the autogenerated stub
    }
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $session = \Yii::$app->session;
            if ($session->get('image')){
                $this->image = 'assets/images/'.$session->get('image');
            }

        }
        else{
            $session = \Yii::$app->session;
            if ($session->get('image')){
                $this->image = 'assets/images/'.$session->get('image');
            } else{
                $this->image = Products::findOne(['id'=>$this->id])->image;
            }

        }// TODO: Change the autogenerated stub
        return true;
    }
    public function afterSave($insert, $changedAttributes)
    {
        $session = \Yii::$app->session;
        $session->set('image',null);; // TODO: Change the autogenerated stub
    }
}