<?php


namespace admin\models;


use yii\db\ActiveRecord;

class Products extends ActiveRecord
{
    public static function tableName()
    {
        return 'products'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [
                ['title','price','barcode','category_id','short_description'], 'required',
            ],
            [
                ['image','popular'],'safe'
            ]
        ]; // TODO: Change the autogenerated stub
    }
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $session = \Yii::$app->session;
            $this->image = 'assets/images/'.$session->get('image');
            $session->set('image',null);
        }
        else{
            $session = \Yii::$app->session;
            $this->image = 'assets/images/'.$session->get('image');
            $session->set('image',null);
        }// TODO: Change the autogenerated stub
        return true;
    }
}