<?php


namespace admin\models;


use admin\controllers\ApiController;
use yii\db\ActiveRecord;

class StoresModel extends ActiveRecord
{
    public static function tableName()
    {
        return 'stores'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['id','lat','lng'], 'safe'],
            [['address'],'required']
        ]; // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->lat = ApiController::getLatLonByAddress($this->address)[0];
        $this->lng = ApiController::getLatLonByAddress($this->address)[1];
        return true; // TODO: Change the autogenerated stub
    }
}