<?php


namespace admin\models;


use admin\controllers\ApiController;
use yii\db\ActiveRecord;

class StoresModel extends ActiveRecord
{
    public static function tableName()
    {
        return 'stores'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['id','lat','lng','image'], 'safe'],
            [['address','title'],'required']
        ]; // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->lat = ApiController::getLatLonByAddress($this->address)[0];
        $this->lng = ApiController::getLatLonByAddress($this->address)[1];
        $session = \Yii::$app->session;
        if ($this->isNewRecord){
            if ($session->get('store_image')){
                $this->image = 'assets/stores/images/'.$session->get('store_image');
            }
        } else{
            if ($session->get('store_image')!=null || trim($session->get('store_image'))!=''){
                $this->image = 'assets/stores/images/'.$session->get('store_image');
            } else{
                $this->image = StoresModel::findOne(['id'=>$this->id])->image;
            }
        }
        return true; // TODO: Change the autogenerated stub
    }
}