<?php


namespace admin\models;


use yii\db\ActiveRecord;

class StoreProductsModel extends ActiveRecord
{
    public static function tableName()
    {
        return 'store_products'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['id','amount','price','grams'],'safe'],
            [['store_id','product_id','product_title'],'required']
        ]; // TODO: Change the autogenerated stub
    }
}