version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    ports:
      - "8099:8080"
    links:
      - php-fpm
    volumes:
      - ./:/var/www:cached
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    links:
      - mysql
    volumes:
      - ./:/var/www:cached
    environment:
      - "DB_PORT=3306"
      - "MYSQL_ROOT_PASSWORD:secret"
      - "MYSQL_USER:root"
      - "MYSQL_PASSWORD:secret"
      - "MYSQL_DATABASE:software"
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www:cached
    environment:
      - "DB_PORT=3306"
      - "MYSQL_ROOT_PASSWORD:secret"
      - "MYSQL_USER:root"
      - "MYSQL_PASSWORD:secret"
      - "MYSQL_DATABASE:software"
    links:
      - mysql
    working_dir: /var/www
    tty: true
  mysql:
    image: mysql:5.6
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=software"
    ports:
      - "3367:3306"
    tty: true