<?php


namespace common\models;


use yii\db\ActiveRecord;

class CategoryContentModel extends ActiveRecord
{
    public static function tableName()
    {
        return 'mobile.categories_content'; // TODO: Change the autogenerated stub
    }
}