<?php


namespace common\models;


use yii\db\ActiveRecord;

class MainContentModel extends ActiveRecord
{
    public static function tableName()
    {
        return 'mobile.main_content'; // TODO: Change the autogenerated stub
    }
}