<?php


namespace common\models;


use yii\db\ActiveRecord;

class MobileNotes extends ActiveRecord
{
    public static function tableName()
    {
        return 'mobile.notes'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
           [['id','done'], 'safe'],
            [['note'], 'required']
        ]; // TODO: Change the autogenerated stub
    }
}